<?php

define('SIREN_VERSION', '1.00.00');

define('SIREN_TYPE_ERROR', 0);
define('SIREN_TYPE_SUCCESS', 1);
define('SIREN_TYPE_LOG', 2);
define('SIREN_TYPE_NOTICE', 3);

define('SIREN_ALERT_NEVER', -1);
define('SIREN_ALERT_ALWAYS', 0);
define('SIREN_ALERT_TIMES', 5);

define('SIREN_RESPONSE_ERROR', 1);
define('SIREN_RESPONSE_SUCCESS', 0);

define('SIREN_PACKAGE_FIXED_LENGTH', 2);
define('SIREN_MAX_UDP_PACKAGE_SIZE', 65507);
define('SIREN_MAX_CHAR_VALUE', 255);
define('SIREN_MAX_UNSIGNED_SHORT_VALUE', 65535);
define('SIREN_MAX_MODULE_LENGTH', 100);
define('SIREN_MAX_SUBMODULE_LENGTH', 100);
define('SIREN_MAX_MSG_LENGTH', 5000);

define('SIREN_NOTIFICATION_NO', 0);
define('SIREN_NOTIFICATION_EMAIL', 1);
define('SIREN_NOTIFICATION_SMS', 2);
define('SIREN_NOTIFICATION_WECHAT', 3);
define('SIREN_NOTIFICATION_ALL', 9);
